### ISSUE TITLE
Discovery fails if a device does not have a servicelist

### ISSUE THREAD

**Issue by dheijl** [jakobhellermann/rupnp#1]
When a device, like a Philips Hue bridge, has no services to advertise, the method `devices.try_next()` throws an unrecoverable error:

_Error: XmlMissingElement("device", "serviceList")_

aborting any further device discovery on the network, unless I am missing something?

Thanks for a very well designed library!

**Comment by jakobhellermann** [comment]
Thanks for the PR ^^
Published as 0.1.7.
