### ISSUE TITLE
Bump to a new release as abde2a contains an important fix

### ISSUE THREAD

**Issue by inetic** [jakobhellermann/rupnp#8]
I am behind the Huawei EchoLife HG8245H router and the [`Service::action` function](https://github.com/jakobhellermann/rupnp/blob/1.0.0/src/service.rs#L105) is returning `HttpErrorCode(500)` when I'm on commit 2209da65b4352824f5402cea7eec978bc5995402 (one with the 1.0.0 tag).

Fortunately for me, this issue has been fixed by @stanislav-omelchenko in commit abde2a32c80f99e6d76b0a969b05a431f357b538.

Could you please bump the version in crates to contain this fix?

**Comment by jakobhellermann** [comment]
Sure, I released a new version v1.1.0
