### ISSUE TITLE
SCPD fails when an allowedValueRange maximum is an empty string

### ISSUE THREAD

**Issue by Silvea12** [jakobhellermann/rupnp#9]
In trying to set up a system with a friend's router (so I am unable to rigorously test), I found that when parsing StateVariables when calling `service.scpd()`, I got this error: Invalid response: cannot parse integer from empty string

Turns out, in their WANIPConn1 service, the Uptime state variable had no maximum defined. Specifically:

```
<stateVariable sendEvents="no">
  <name>Uptime</name>
  <dataType>ui4</dataType>
  <defaultValue>0</defaultValue>
  <allowedValueRange>
    <minimum>0</minimum>
    <maximum/>
    <step>1</step>
  </allowedValueRange>
</stateVariable>
```

When parsing, `maximum` here causes the parsing to fail.

The specific router is a TP-Link TD-W9970, model number 4.0.
It also reproduces on the TP-Link Archer VR1600v (unknown model version)

I'm not sure how this would best be represented, but if informed how to I'm happy to do a PR myself.

The specific error location is in `scpd::state_variable::range_from_xml()` when parsing maximum by calling `utils::parse_node_text()`.

**Comment by Silvea12** [comment]
As a note, I realize that having `maximum` as empty is outside of spec for `allowedValueRange`, but I'm not sure how I'm meant to handle it here, as this seems to apply to every TP-Link router I can find.

**Comment by jakobhellermann** [comment]
I think a missing `maximum` can be reasonably treated as having no maximum, even if it's not in the spec.
It's been a while since I've looked at the code but I think you could change change these lines
https://github.com/jakobhellermann/rupnp/blob/1ff4881a315f7a2ddee62d79267720bd1cb429f9/src/scpd/state_variable.rs#L188-L189

to
```rust
    let minimum = utils::parse_node_text(minimum).unwrap_or(i32::MIN);
    let maximum = utils::parse_node_text(maximum).unwrap_or(i32::MAX);
```

The way, if it fails to parse the empty string as a number it will just fallback to allowing everything.

I'd be happy to merge a PR if you want to fix it.

**Comment by Silvea12** [comment]
I'll need to peek at it closer as it'll need type info passed to get reasonable minimums/maximums based on the field type (currently not acknowledged by the underlying type used for range) but I'll see what I can do. I'll gladly send a PR later this week when I get some time.

-------- Original Message --------

**Comment by Silvea12** [comment]
@jakobhellermann Since as is default is using String, should I just change range to do strings? I can then do valid defaults based on the output without worry. I'd need to switch `RangeInclusive<>` to a tuple or struct, but then I can either leave the string blank and let the user handle it, or fall back to a parsed default based on the data type, as currently it doesn't seem like the library actually parses out the state variable's type to the correct underlying type (which includes fixed point ints and floats, as well as complex date/time/timezone data)
